version: '3'

services:
  # MySQL
  snipe-mysql:
    image: mysql:5.6
    container_name: snipe-mysql
    volumes:
      - db-vol:/var/lib/mysql
    env_file:
      - ./.env
    expose:
      - "3306"

  snipe-it:
    image: snipe/snipe-it
    container_name: snipe-it
    ports:
      - "3051:80"
    env_file:
      - ./.env
    depends_on:
      - snipe-mysql

volumes:
  db-vol:
